app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from . import views, errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    from flask import render_template_string,render_template
    return dict(Permission=Permission,render_template_string=render_template_string,render_template=render_template)

app/main/views.py
from datetime import datetime,date
from flask import render_template, session, redirect, url_for, flash, request, current_app, abort, make_response,jsonify
from . import main
from .. import db
from ..models import User,Role,Article,Permission,ArticleType,Tags,CreativeWork
from flask_login import login_required,current_user
from ..decorators import admin_required
import os

import os

@main.route('/', methods=['GET','POST'])
def index():
    # if current_user.can(Permission.WRITE) and form.validate_on_submit():
    #     if form.submit.data == True:
    #         article = Article(title=form.title.data,body=form.body.data,author=current_user._get_current_object(),publish_date=datetime.utcnow())
    #         db.session.add(article)
    #         db.session.commit()
    #         return redirect(url_for('.index'))
    #     if form.save_draft.data == True:
    #         article = Article(title=form.body.title,body=form.body.data,author=current_user._get_current_object())
    #         db.session.add(article)
    #         db.session.commit()
    #         return redirect(url_for('.index'))
    page = request.args.get('page',1,type=int)
    pagination=Article.query.order_by(Article.publish_date.desc()).paginate(page,
        per_page=current_app.config['ESKIMOTV_ARTICLES_PER_PAGE'],
        error_out=False)

    # articles = pagination.items
    articles = Article.query.order_by(Article.publish_date.desc()).filter(Article.publish_date <= datetime.utcnow(),Article.is_published==True).all()
    all_articles={}
    for type in ArticleType.query.all():
        all_articles[type.name] = type.articles.order_by(Article.publish_date.desc()).filter(Article.publish_date <= datetime.utcnow(),Article.is_published==True).all()
    return render_template('main/home.html.j2',articles=articles,all_articles=all_articles,pagination=pagination,time=datetime.utcnow())

@main.route('/articles/<int:year>/<int:month>/<int:day>/<string:title_slug>/')
@main.route('/articles/<string:title_slug>/')
def article(title_slug,**kwargs):
    article = Article.query.filter_by(title_slug=title_slug).first_or_404()
    if not article.published and not current_user.is_administrator() and not current_user.can(Permission.EDIT) and not current_user == article.author:
        abort(404)
    return render_template('main/article.html.j2',article=article)

@main.route('/user/<id>/')
def profile(id):
    user = User.query.filter_by(id=id).first()
    def query_for_user():
        return user.articles.filter_by(published=True)
    def query_for_requests_to_publish():
        if current_user.can(Permission.PUBLISH):
            return Article.query.filter_by(request_to_publish=True)
        else:
            abort(403,description="You don't have permission to publish.")
    def query_for_all_unpublished():
        if current_user.can(Permission.PUBLISH):
            return Article.query.filter_by(is_published=False)
    def query_for_my_drafts():
        return Article.query.filter_by(author=user).filter_by(is_published=False)
    display_options = {
        'none':query_for_user,
        "waiting_for_publication":query_for_requests_to_publish,
        "unpublished":query_for_all_unpublished,
        "my_drafts":query_for_my_drafts
    }
    display = 'none'
    if current_user.is_authenticated and current_user == user:
        display = request.cookies.get('display','none')
        if (not current_user.can(Permission.PUBLISH) and display in ["waiting_for_publication","unpublished"]) or (current_user.can(Permission.PUBLISH) and display in ["my_drafts"]):
            display = 'none'
    query = display_options[display]()
    page = request.args.get('page',1,type=int)
    current_app.logger.info(query)
    pagination = query.order_by(Article.publish_date.desc()).paginate(page,
        per_page=current_app.config['ESKIMOTV_ARTICLES_PER_PAGE'],
        error_out=False)
    articles = pagination.items
    return render_template('main/user.html.j2',user=user, articles=articles,display=display,pagination=pagination,no_index=True)

@main.route('/toggle_user_display')
def toggle_user_display():
    response = make_response(redirect(url_for('main.profile',id=request.args.get('user_id'))))
    response.set_cookie('display',request.args.get('display','none'),max_age=30*24*60*60)
    return response


@main.route('/reviews/')
def reviews():
        page = request.args.get('page',1,type=int)
        type = ArticleType.query.filter_by(name="Review").first()
        pagination=type.articles.order_by(Article.publish_date.desc()).filter(Article.publish_date <= datetime.utcnow(),Article.is_published==True).paginate(page,
            per_page=current_app.config['ESKIMOTV_ARTICLES_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('main/archive_template.html.j2',articles=articles,pagination=pagination,time=datetime.utcnow(),no_index=True)

@main.route('/editorials/')
def editorials():
        page = request.args.get('page',1,type=int)
        type = ArticleType.query.filter_by(name="Editorial").first()
        pagination=type.articles.order_by(Article.publish_date.desc()).filter(Article.publish_date <= datetime.utcnow(),Article.is_published==True).paginate(page,
            per_page=current_app.config['ESKIMOTV_ARTICLES_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('main/archive_template.html.j2',articles=articles,pagination=pagination,time=datetime.utcnow(),no_index=True)

@main.route('/news/')
def news():
        page = request.args.get('page',1,type=int)
        type = ArticleType.query.filter_by(name="News").first()
        pagination=type.articles.order_by(Article.publish_date.desc()).filter(Article.publish_date <= datetime.utcnow(),Article.is_published==True).paginate(page,
            per_page=current_app.config['ESKIMOTV_ARTICLES_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('main/archive_template.html.j2',articles=articles,pagination=pagination,time=datetime.utcnow(),no_index=True)

@main.route('/archive/')
def archive():
        page = request.args.get('page',1,type=int)
        pagination=Article.query.order_by(Article.publish_date.desc()).filter(Article.publish_date <= datetime.utcnow(),Article.is_published==True).paginate(page,
            per_page=current_app.config['ESKIMOTV_ARTICLES_PER_PAGE'],
            error_out=False)
        articles = pagination.items
        return render_template('main/archive_template.html.j2',articles=articles,pagination=pagination,time=datetime.utcnow(),no_index=True)

@main.route('/about/')
def about_us():
    description = "Learn about who we are, the authors that contribute to our site, and also about how to contact us."
    title = "About Us"
    r = Role.query.filter_by(name="Publisher").first()
    r2 = Role.query.filter_by(name="Administrator").first()
    publishers = User.query.filter((User.role == r) | (User.role == r2))
    return render_template('main/about-us.html.j2', publishers = publishers, title=title,description=description)

@main.route('/results/')
def search_results():
    description = f"Search results for articles on {current_app.config['TITLE']}."
    title = "Search Results"
    return render_template('main/search-results.html.j2',title=title,description=description,no_index=True)


@main.route('/feed.xml')
def rss_feed():
    return None

app/templates/main/about-us.html.j2
{% extends "default.html.j2" %}

{% block title %}{{ super() }}: {{ title }}{% endblock %}

{% block header %}<h1>{{ title }}</h1>{% endblock %}

{% block page_content %}
<p>{{ config.TITLE }} is the collaborative work of Jason Escamilla and David Scott. Fans of all forms of culture, our platform was built as a means of opening up a discussion and providing a space for exploring truth in art. It is our firm belief that art does not happen in a vacuum and that you cannot create something without making a statement. What you'll find here is a mixture of thoughtful reviews that try to gauge the quality of a film above and beyond just how much the reviewer enjoyed it and editorials that ask important questions about the works they discuss.</p>

<p>By engaging with movies beyond the simple question of whether or not they were enjoyable, we hope to find more meaning in the media we consume because it is important to think about what you take in and put back out. To contact us, request a review of a movie, show, book, or game, or especially if you are interested in contributing, please email us at <a href="mailto:{{ config.EMAIL }}">{{ config.EMAIL }}</a>.</p>

<h2>Our Editors</h2>

<div>
{% for publisher in publishers %}
  <div class="container portfolio">
  	<div class="bio-info">
  		<div class="row">
  			<div class="col-md-3">
  				<div class="row">
  					<div class="col-md-12">
  						<div class="bio-image">
  							<img class="rounded-circle" src="{{ publisher.gravatar(size=400) }}" alt="{{ publisher.first_name }} profile pic.">
  						</div>
  					</div>
  				</div>
  			</div>
  			<div class="col-md-9">
  				<div class="bio-content">
  					<h3 class="bio-header"><a href="{{ url_for('main.profile', id = publisher.id) }}">{{ publisher.first_name }} {{ publisher.last_name }}</a></h3>
  					<h5 class="bio-subheader">{{ publisher.role.name }}</h5>
  					<p class="bio-content">{{ publisher.about_me }}</p>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
{% endfor %}
</div>

{% endblock %}

app/templates/main/archive_template.html.j2
{% extends "default.html.j2" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "includes/macros.html.j2" as macros %}

{% block title %}{{ super() }}: Reviews{% endblock %}

{% block page_content %}
<div class="home">

  <h1 class="page-heading">Reviews{% if pagination %} - Page {{ pagination.page }} of {{ pagination.pages }}{% endif %}</h1>

    <!-- BEGIN BLOG -->
    <div class="row row-centered">
        {% for post in articles %}
        {{ render_template('includes/post-panel.html.j2',post=post) }}
        {% endfor %}
    </div>
    <!-- END BLOG -->
    <!-- BLOG NAVIGATION -->
    {{ macros.pagination_widget(pagination, request.url_rule.endpoint) }}
    {#<div class="row row-centered">
        <div class="col-md-4 col-sm-6 col-centered">
            <div class="btn-group btn-group-justified">
                {% if paginator.previous_page %}<a href="{{ paginator.previous_page_path }}" class="btn btn-primary">&lt; Newer</a>{% endif %}
                <a href="/" class="btn btn-primary">Home</a>
                {% if paginator.next_page %}<a href="{{ paginator.next_page_path }}" class="btn btn-primary">Older &gt;</a>{% else %}<a href="/archive/" class="btn btn-primary">Full Archive</a>{% endif %}
            </div>
        </div>
    </div>#}
    <!-- BLOG NAVIGATION -->

  <p class="rss-subscribe">subscribe <a href="{{ url_for('main.rss_feed',_external=True) }}">via RSS</a></p>

</div>
{% endblock %}

app/templates/main/article.html.j2
{% extends "default.html.j2" %}
{% import "includes/macros.html.j2" as macros with context %}


{% block title %}{% if not article.published %}Draft: {% endif %}{{ super() }}: {{ article.title }}{% endblock %}

{% block page_content %}
<div class="row">
  {% if (article.published and current_user.can(Permission.PUBLISH)) or (not article.is_published and (current_user.can(Permission.EDIT) or current_user == article.author)) %}
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Publisher Options</h5>
        <!--<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
        <a href="{{ url_for('admin.edit_article',id=article.id) }}" class="btn btn-primary">Edit Article</a>
        {% if current_user.can(Permission.PUBLISH) and article.published %}<a href="{{ url_for('admin.unpublish',article_id=article.id) }}" class="btn btn-warning">Un-Publish</a>{% endif %}
        {% if article.draft %}
        <a class="btn btn-secondary" href="{{ url_for('admin.edit_article',id=article.id,edit='draft') }}">Resume Draft</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endif %}
  <div class="col-lg-8">
    <div class="post">
      <article class="post-content">
        <header class="post-header">
          <h2 class="post-title">{% if not article.published %}Draft Article: {% endif %}{% if article.youtube %}Video: {% endif %}{{ article.title }}</h2>
          <p class="post-meta">{{ article.type.name | capitalize }} • {{ article.publish_date.strftime("%b %-d, %Y") }} • Author: <a href="{{ url_for('main.profile', id = article.author.id) }}">{{ article.author.first_name }} {{ article.author.last_name }}</a></p>
          <p class="post-meta">{% for tag in article.tags %}<span class="badge badge-pill badge-secondary">{{ tag.name }}</span> {% endfor %}</p>
          {% include "includes/social-media.html" %}
        </header>
        {% if article.youtube %}{{ macros.media(type="youtube",src=article.youtube,feature=True) }}{% else %}<img class="img-responsive webfeedsFeaturedVisual" src="{{ resized_img_src(article.image,width=994,height=466,mode='crop') }}" alt="{{ article.title }} Cover">{% endif %}
        {% if not article.published and article.draft %}{{ article.draft }}{% endif %}{{ article.body }}
        {% if article.rating %}
        <table class="table">
          <tbody>
            <tr>
              <td><b>Final Verdict</b>:</td><td>{{ article.final_verdict | e }}</td>
            </tr>
            <tr>
              <td><b>Rating</b>:</td><td>{{ article.letter_rating }}</td>
            </tr>
          </tbody>
        </table>
        {% endif %}
      </article>
      {% include "includes/social-media.html" %}
      <br>
      <hr class="clear">
      <h2 id="comments">Comments</h2>
      <div id="disqus_thread"></div>
      <script>
          /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
          var disqus_config = function () {
          this.page.url = "{{ self.pageurl() }}";
          this.page.identifier = "{{ article.title_slug }}";
          };
          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://eskimotv.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="sidebar-nav">
      {#<h3>Sponsors</h3>
      {% include ads.html %}#}
      <!--googleoff: all-->
      <!--noindex-->
      <h3>Related Articles</h3>
      {% for related_article in article.related_articles %}
      {{ render_template('includes/related_articles.html.j2',related_article=related_article) }}
      {% endfor %}
      <!--/noindex-->
      <!--googleon: all-->
    </div>
  </div>
</div>
{% endblock %}

app/templates/main/edit_user.html.j2
{% extends "default.html.j2" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}EskimoTV: Edit Profile{% endblock %}

{% block header %}
<h1>Edit Your Profile</h1>
{% endblock %}

{% block page_content %}
<div class="row">
  <div class="col-md-4">
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/main/home.html.j2
{% extends "default.html.j2" %}

{% block title %}{{ super() }}: Home{% endblock %}

{% block page_content %}
<div class="home">
  <div class="page-heading d-none d-lg-block">
    <h1>Icy & Chilly Reviews and Editorials</h1>
    <h3 class="page-meta">Your home for movies, entertainment, and more!</h3>
  </div>

  <div id="home-slider" class="owl-carousel">
    {% for article in articles[:14] %}
    <div class="item">
      <a href="{{ article.url }}">
        <div class="slide-text">
          <h2><span>{{ article.title }} / {% if article.youtube %}Video {% endif %}{{ article.type.name | capitalize }}</span></h2>
          <span class="slide-blurb"><span>{{ article.blurb }}</span></span>
        </div>
        <div class="slide-image">
          <img {% if not loop.first %}class="lazyOwl" data-src="{{ resized_img_src(article.image,width=1110,height=555,mode='crop',quality="70") }}"{% endif %}{% if loop.first %}src="{{ resized_img_src(article.image,width=1110,height=555,mode='crop',quality="70") }}"{% endif %} alt="{{ article.title }}">
        </div>
      </a>
    </div>
    {% endfor %}
  </div>

  <h2>Recent Reviews</h2>

  <div class="row">
    {% for post in all_articles['Review'][:6] %}
    {{ render_template('includes/post-panel.html.j2',post=post) }}
    {% endfor %}
  </div>

  <h2>Recent News</h2>

  <div class="row">
    {% for post in all_articles['News'][:3] %}
    {{ render_template('includes/post-panel.html.j2',post=post) }}
    {% endfor %}
  </div>

  <h2>Recent Editorials</h2>

  <div class="row">
    {% for post in all_articles['Editorial'][:3] %}
    {{ render_template('includes/post-panel.html.j2',post=post) }}
    {% endfor %}
  </div>

  <p class="rss-subscribe">subscribe <a href="">via RSS</a></p>
</div>
{% endblock %}

app/templates/main/search-results.html.j2
{% extends "default.html.j2" %}

{% block title %}{{ super() }}: {{ title }}{% endblock %}

{% block header %}<h1>{{ title }}</h1>{% endblock %}

{% block page_content %}
<div>
  <gcse:searchresults-only></gcse:searchresults-only>
</div>

<p class="rss-subscribe">subscribe <a href="{{ url_for('main.rss_feed') }}">via RSS</a></p>
{% endblock %}

app/templates/main/user.html.j2
{% extends "default.html.j2" %}
{% import "includes/macros.html.j2" as macros %}

{% block title %}EskimoTV: {{ user.username }}{% endblock %}

{% block header %}
<div class="row page-heading">
  <div class="col-lg-4">
    <img class="rounded" src="{{ user.gravatar(size=400) }}">
  </div>
  <div class="col-lg-8">
    <h1>{% if user.first_name %}{{ user.first_name }}{% if user.last_name %} {{ user.last_name }}{% endif %}{% else %}No Name{% endif %}</h1>
    {% if user.first_name or user.last_name %}
    <p>
      {{ user.username }} | {{ user.role.name }}
    </p>
    {% endif %}
    {% if current_user.is_administrator() or current_user.id == user.id %}
    <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
    {% endif %}
    {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
    <p>
      Member since {{ moment(user.member_since).format('L') }}.
      Last seen {{ moment(user.last_seen).fromNow() }}.
    </p>
    <p>
      {% if user==current_user and user.can(Permission.WRITE) %}
      <a class="btn btn-success" href="{{ url_for('admin.new_article') }}">New Article</a>
      {% endif %}
      {% if user == current_user %}
      <a class="btn btn-primary" href="{{ url_for('admin.edit_profile') }}">Edit Profile</a>
      {% endif %}
      {% if current_user.is_administrator() %}
      <a class="btn btn-danger" href="{{ url_for('admin.edit_profile_admin', id=user.id) }}">Edit Profile [Admin]</a>
      {% endif %}
    </p>
  </div>
</div>
{% endblock %}
{% block page_content %}
<div class="row">
  <div class="col-lg-12">
    <ul class="nav nav-tabs nav-fill">
        <li class="nav-item"><a class="nav-link{% if display == 'none' %} active{% endif %}" href="{{ url_for('main.toggle_user_display',user_id=user.id) }}">{% if user == current_user %}My{% else %}{{ user.username }}'s{% endif %} Articles</a></li>
        {#{% if current_user == user %}<li class="nav-item"><a class="nav-link{% if display == "followed" %} active{% endif %}" href="{{ url_for('main.toggle_user_display',display="followed",user_id=user.id) }}">Followed Authors</a></li>{% endif %}#}
        {% if current_user.can(Permission.PUBLISH) and user == current_user %}<li class="nav-item"><a class="nav-link{% if display == "waiting_for_publication" %} active{% endif %}" href="{{ url_for('main.toggle_user_display',display="waiting_for_publication",user_id=user.id) }}">Requests to Publish</a></li>{% endif %}
        {% if current_user.can(Permission.PUBLISH) and user == current_user %}<li class="nav-item"><a class="nav-link{% if display == "unpublished" %} active{% endif %}" href="{{ url_for('main.toggle_user_display',display="unpublished",user_id=user.id) }}">All Drafts</a></li>{% elif current_user.can(Permission.WRITE) and current_user == user %}<li class="nav-item"><a class="nav-link{% if display == "my_drafts" %} active{% endif %}" href="{{ url_for('main.toggle_user_display',display="my_drafts",user_id=user.id) }}">My Drafts</a></li>{% endif %}
    </ul>
    {% include "includes/articles.html.j2" %}
  </div>
</div>
<!-- BLOG NAVIGATION -->
{{ macros.pagination_widget(pagination, request.url_rule.endpoint, id=user.id) }}
{% endblock %}